//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasketDetailsType", propOrder = {
		"productCode",
		"productsku",
	    "cost",
	    "quantity",
	    "productName",
	    "couponDetails"
})
public class BasketDetailsType
    implements Serializable, ToString
{

	 	@XmlElement(name = "ProductSKU")
	    protected String productsku;
	    @XmlElement(name = "ProductCode")
	    protected String productCode;
	    @XmlElement(name = "Cost")
	    protected Float cost;
	    @XmlElement(name = "Quantity")
	    protected Long quantity;
	    @XmlElement(name = "ProductName")
	    protected String productName;
    
    @XmlElement(name= "couponDetails")
	protected List<CouponDetailsType> couponDetails;
    
 

    public List<CouponDetailsType> getCouponDetails() {
		return couponDetails;
	}

	public void setCouponDetails(List<CouponDetailsType> couponDetails) {
		this.couponDetails = couponDetails;
	}
	
	
	
	/**
     * Gets the value of the productsku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */

    public String getProductsku() {
		return productsku;
	}
    
    /**
    * Sets the value of the productsku property.
    * 
    * @param value
    *     allowed object is
    *     {@link String }
    *     
    */

	public void setProductsku(String productsku) {
		this.productsku = productsku;
	}
	
	/**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	

	public String getProductCode() {
		return productCode;
	}
	
	/**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	

	/**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCost(Float value) {
        this.cost = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantity(Long value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getProductName() {
		return productName;
	}

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
  
   	public void setProductName(String productName) {
		this.productName = productName;
	}
    
    
    

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

   

	public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theProductSKU;
            theProductSKU = this.getProductsku();
            strategy.appendField(locator, this, "productsku", buffer, theProductSKU);
        }
        {
            String theProductCode;
            theProductCode = this.getProductCode();
            strategy.appendField(locator, this, "productCode", buffer, theProductCode);
        }
        {
            Float theCost;
            theCost = this.getCost();
            strategy.appendField(locator, this, "cost", buffer, theCost);
        }
        {
            Long theQuantity;
            theQuantity = this.getQuantity();
            strategy.appendField(locator, this, "quantity", buffer, theQuantity);
        }
        {
        	String theProductName;
            theProductName = this.getProductName();
            strategy.appendField(locator, this, "productName", buffer, theProductName);
        }
        return buffer;
    }

}
