//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.payment.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.payment.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SrPayResponse }
     * 
     */
    public SrPayResponse createSrPayResponse() {
        return new SrPayResponse();
    }

    /**
     * Create an instance of {@link RegResponseDataType }
     * 
     */
    public RegResponseDataType createRegResponseDataType() {
        return new RegResponseDataType();
    }

    /**
     * Create an instance of {@link ResponseDataType }
     * 
     */
    public ResponseDataType createResponseDataType() {
        return new ResponseDataType();
    }

    /**
     * Create an instance of {@link SrPayRequest }
     * 
     */
    public SrPayRequest createSrPayRequest() {
        return new SrPayRequest();
    }

    /**
     * Create an instance of {@link DeviceProfileType }
     * 
     */
    public DeviceProfileType createDeviceProfileType() {
        return new DeviceProfileType();
    }

    /**
     * Create an instance of {@link RegRequestDataType }
     * 
     */
    public RegRequestDataType createRegRequestDataType() {
        return new RegRequestDataType();
    }

    /**
     * Create an instance of {@link SalesRequestDataType }
     * 
     */
    public SalesRequestDataType createSalesRequestDataType() {
        return new SalesRequestDataType();
    }

    /**
     * Create an instance of {@link DepositRequestDataType }
     * 
     */
    public DepositRequestDataType createDepositRequestDataType() {
        return new DepositRequestDataType();
    }

    /**
     * Create an instance of {@link CardDetailsType }
     * 
     */
    public CardDetailsType createCardDetailsType() {
        return new CardDetailsType();
    }

    /**
     * Create an instance of {@link CustIPType }
     * 
     */
    public CustIPType createCustIPType() {
        return new CustIPType();
    }

    /**
     * Create an instance of {@link OtherDataType }
     * 
     */
    public OtherDataType createOtherDataType() {
        return new OtherDataType();
    }

    /**
     * Create an instance of {@link TerminalInfoType1ToBeRemoved }
     * 
     */
    public TerminalInfoType1ToBeRemoved createTerminalInfoType1ToBeRemoved() {
        return new TerminalInfoType1ToBeRemoved();
    }

    /**
     * Create an instance of {@link SalesTransactionDataType }
     * 
     */
    public SalesTransactionDataType createSalesTransactionDataType() {
        return new SalesTransactionDataType();
    }

    /**
     * Create an instance of {@link TerminalDataType }
     * 
     */
    public TerminalDataType createTerminalDataType() {
        return new TerminalDataType();
    }

    /**
     * Create an instance of {@link BasketDetailsType }
     * 
     */
    public BasketDetailsType createBasketDetailsType() {
        return new BasketDetailsType();
    }

    /**
     * Create an instance of {@link TransactionDataType }
     * 
     */
    public TransactionDataType createTransactionDataType() {
        return new TransactionDataType();
    }

}
