//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for OtherDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrepaidBalance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="RewardBalance" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="ReceiptMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RewardsEarned" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="RewardsRedeemed" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherDataType", propOrder = {
    "prepaidBalance",
    "rewardBalance",
    "receiptMessage",
    "rewardsEarned",
    "rewardsRedeemed"
})
public class OtherDataType
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PrepaidBalance")
    protected Float prepaidBalance;
    @XmlElement(name = "RewardBalance")
    protected Float rewardBalance;
    @XmlElement(name = "ReceiptMessage")
    protected String receiptMessage;
    @XmlElement(name = "RewardsEarned")
    protected Float rewardsEarned;
    @XmlElement(name = "RewardsRedeemed")
    protected Float rewardsRedeemed;

    /**
     * Gets the value of the prepaidBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPrepaidBalance() {
        return prepaidBalance;
    }

    /**
     * Sets the value of the prepaidBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPrepaidBalance(Float value) {
        this.prepaidBalance = value;
    }

    /**
     * Gets the value of the rewardBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRewardBalance() {
        return rewardBalance;
    }

    /**
     * Sets the value of the rewardBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRewardBalance(Float value) {
        this.rewardBalance = value;
    }

    /**
     * Gets the value of the receiptMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptMessage() {
        return receiptMessage;
    }

    /**
     * Sets the value of the receiptMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptMessage(String value) {
        this.receiptMessage = value;
    }

    /**
     * Gets the value of the rewardsEarned property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRewardsEarned() {
        return rewardsEarned;
    }

    /**
     * Sets the value of the rewardsEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRewardsEarned(Float value) {
        this.rewardsEarned = value;
    }

    /**
     * Gets the value of the rewardsRedeemed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRewardsRedeemed() {
        return rewardsRedeemed;
    }

    /**
     * Sets the value of the rewardsRedeemed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRewardsRedeemed(Float value) {
        this.rewardsRedeemed = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Float thePrepaidBalance;
            thePrepaidBalance = this.getPrepaidBalance();
            strategy.appendField(locator, this, "prepaidBalance", buffer, thePrepaidBalance);
        }
        {
            Float theRewardBalance;
            theRewardBalance = this.getRewardBalance();
            strategy.appendField(locator, this, "rewardBalance", buffer, theRewardBalance);
        }
        {
            String theReceiptMessage;
            theReceiptMessage = this.getReceiptMessage();
            strategy.appendField(locator, this, "receiptMessage", buffer, theReceiptMessage);
        }
        {
            Float theRewardsEarned;
            theRewardsEarned = this.getRewardsEarned();
            strategy.appendField(locator, this, "rewardsEarned", buffer, theRewardsEarned);
        }
        {
            Float theRewardsRedeemed;
            theRewardsRedeemed = this.getRewardsRedeemed();
            strategy.appendField(locator, this, "rewardsRedeemed", buffer, theRewardsRedeemed);
        }
        return buffer;
    }

}
