//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesRequestDataType", propOrder = {
    "custIP",
    "salesTransactionData",
    "cardDetails",
    "cashierCode"
})
public class SalesRequestDataType
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CustIP", required = true)
    protected CustIPType custIP;
    @XmlElement(name = "SalesTransactionData", required = true)
    protected SalesTransactionDataType salesTransactionData;
    @XmlElement(name = "CardDetails", required = true)
    protected CardDetailsType cardDetails;
    @XmlElement(name = "CashierCode", required = true)
    protected String cashierCode;

    /**
     * Gets the value of the custIP property.
     * 
     * @return
     *     possible object is
     *     {@link CustIPType }
     *     
     */
    public CustIPType getCustIP() {
        return custIP;
    }

    /**
     * Sets the value of the custIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIPType }
     *     
     */
    public void setCustIP(CustIPType value) {
        this.custIP = value;
    }

    /**
     * Gets the value of the salesTransactionData property.
     * 
     * @return
     *     possible object is
     *     {@link SalesTransactionDataType }
     *     
     */
    public SalesTransactionDataType getSalesTransactionData() {
        return salesTransactionData;
    }

    /**
     * Sets the value of the salesTransactionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesTransactionDataType }
     *     
     */
    public void setSalesTransactionData(SalesTransactionDataType value) {
        this.salesTransactionData = value;
    }

    /**
     * Gets the value of the cardDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CardDetailsType }
     *     
     */
    public CardDetailsType getCardDetails() {
        return cardDetails;
    }

    /**
     * Sets the value of the cardDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardDetailsType }
     *     
     */
    public void setCardDetails(CardDetailsType value) {
        this.cardDetails = value;
    }

    /**
     * Gets the value of the cashierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashierCode() {
        return cashierCode;
    }

    /**
     * Sets the value of the cashierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashierCode(String value) {
        this.cashierCode = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CustIPType theCustIP;
            theCustIP = this.getCustIP();
            strategy.appendField(locator, this, "custIP", buffer, theCustIP);
        }
        {
            SalesTransactionDataType theSalesTransactionData;
            theSalesTransactionData = this.getSalesTransactionData();
            strategy.appendField(locator, this, "salesTransactionData", buffer, theSalesTransactionData);
        }
        {
            CardDetailsType theCardDetails;
            theCardDetails = this.getCardDetails();
            strategy.appendField(locator, this, "cardDetails", buffer, theCardDetails);
        }
        {
            String theCashierCode;
            theCashierCode = this.getCashierCode();
            strategy.appendField(locator, this, "cashierCode", buffer, theCashierCode);
        }
        return buffer;
    }

}
