//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesTransactionDataType", propOrder = {
    "transactionData",
    "basketDetails",
    "tax1",
    "tax2",
    "tax3",
    "tip"
})
public class SalesTransactionDataType
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TransactionData", required = true)
    protected TransactionDataType transactionData;
    @XmlElement(name = "BasketDetails", required = true)
    protected List<BasketDetailsType> basketDetails;
    @XmlElement(name = "Tax1")
    protected float tax1;
    @XmlElement(name = "Tax2")
    protected float tax2;
    @XmlElement(name = "Tax3")
    protected float tax3;
    @XmlElement(name = "Tip")
    protected float tip;

    /**
     * Gets the value of the transactionData property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDataType }
     *     
     */
    public TransactionDataType getTransactionData() {
        return transactionData;
    }

    /**
     * Sets the value of the transactionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDataType }
     *     
     */
    public void setTransactionData(TransactionDataType value) {
        this.transactionData = value;
    }

    /**
     * Gets the value of the basketDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basketDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasketDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasketDetailsType }
     * 
     * 
     */
    public List<BasketDetailsType> getBasketDetails() {
        if (basketDetails == null) {
            basketDetails = new ArrayList<BasketDetailsType>();
        }
        return this.basketDetails;
    }

    /**
     * Gets the value of the tax1 property.
     * 
     */
    public float getTax1() {
        return tax1;
    }

    /**
     * Sets the value of the tax1 property.
     * 
     */
    public void setTax1(float value) {
        this.tax1 = value;
    }

    /**
     * Gets the value of the tax2 property.
     * 
     */
    public float getTax2() {
        return tax2;
    }

    /**
     * Sets the value of the tax2 property.
     * 
     */
    public void setTax2(float value) {
        this.tax2 = value;
    }

    /**
     * Gets the value of the tax3 property.
     * 
     */
    public float getTax3() {
        return tax3;
    }

    /**
     * Sets the value of the tax3 property.
     * 
     */
    public void setTax3(float value) {
        this.tax3 = value;
    }

    /**
     * Gets the value of the tip property.
     * 
     */
    public float getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     */
    public void setTip(float value) {
        this.tip = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            TransactionDataType theTransactionData;
            theTransactionData = this.getTransactionData();
            strategy.appendField(locator, this, "transactionData", buffer, theTransactionData);
        }
        {
            List<BasketDetailsType> theBasketDetails;
            theBasketDetails = (((this.basketDetails!= null)&&(!this.basketDetails.isEmpty()))?this.getBasketDetails():null);
            strategy.appendField(locator, this, "basketDetails", buffer, theBasketDetails);
        }
        {
            float theTax1;
            theTax1 = this.getTax1();
            strategy.appendField(locator, this, "tax1", buffer, theTax1);
        }
        {
            float theTax2;
            theTax2 = this.getTax2();
            strategy.appendField(locator, this, "tax2", buffer, theTax2);
        }
        {
            float theTax3;
            theTax3 = this.getTax3();
            strategy.appendField(locator, this, "tax3", buffer, theTax3);
        }
        {
            float theTip;
            theTip = this.getTip();
            strategy.appendField(locator, this, "tip", buffer, theTip);
        }
        return buffer;
    }

}
