//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 04:20:53 PM IST 
//


package com.payment.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SrPayResponse", propOrder = {
    "authToken",
    "processingCode",
    "regResponseData",
    "salesResponseData",
    "depositResponseData",
    "sendReceiptResponseData",
    "prodListResponseData"
})
@XmlRootElement(name = "SrPayResponse")
public class SrPayResponse
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "AuthToken", required = true)
    protected String authToken;
	@XmlElement(name = "ProcessingCode")
    protected String processingCode;
    @XmlElement(name = "RegResponseData")
    protected RegResponseDataType regResponseData;
    @XmlElement(name = "SalesResponseData")
    protected ResponseDataType salesResponseData;
    @XmlElement(name = "DepositResponseData")
    protected ResponseDataType depositResponseData;
    @XmlElement(name = "SendReceiptResponseData")
    protected ResponseDataType sendReceiptResponseData;
    @XmlElement(name = "ProdListResponseData")
    protected ProdListResponseType prodListResponseData;
	@XmlAttribute(name = "version")
    protected Float version;

    /**
     * Gets the value of the authToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * Sets the value of the authToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthToken(String value) {
        this.authToken = value;
    }

    /**
     * Gets the value of the operationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingCode() {
        return processingCode;
    }

    /**
     * Sets the value of the operationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingCode(String value) {
        this.processingCode = value;
    }

    /**
     * Gets the value of the regResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link RegResponseDataType }
     *     
     */
    public RegResponseDataType getRegResponseData() {
        return regResponseData;
    }

    /**
     * Sets the value of the regResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegResponseDataType }
     *     
     */
    public void setRegResponseData(RegResponseDataType value) {
        this.regResponseData = value;
    }

    /**
     * Gets the value of the salesResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseDataType }
     *     
     */
    public ResponseDataType getSalesResponseData() {
        return salesResponseData;
    }

    /**
     * Sets the value of the salesResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseDataType }
     *     
     */
    public void setSalesResponseData(ResponseDataType value) {
        this.salesResponseData = value;
    }

    /**
     * Gets the value of the depositResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseDataType }
     *     
     */
    public ResponseDataType getDepositResponseData() {
        return depositResponseData;
    }

    /**
     * Sets the value of the depositResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseDataType }
     *     
     */
    public void setDepositResponseData(ResponseDataType value) {
        this.depositResponseData = value;
    }

    
    /**
     * Gets the value of the depositResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseDataType }
     *     
     */
    public ResponseDataType getSendReceiptResponseData() {
        return sendReceiptResponseData;
    }

    /**
     * Sets the value of the depositResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseDataType }
     *     
     */
    public void setSendReceiptResponseData(ResponseDataType value) {
        this.sendReceiptResponseData = value;
    }
    
    
    
    
    
    public ProdListResponseType getProdListResponseData() {
		return prodListResponseData;
	}

	public void setProdListResponseData(ProdListResponseType prodListResponseData) {
		this.prodListResponseData = prodListResponseData;
	}
    
    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theAuthToken;
            theAuthToken = this.getAuthToken();
            strategy.appendField(locator, this, "authToken", buffer, theAuthToken);
        }
        {
            String theProcessingCode;
            theProcessingCode = this.getProcessingCode();
            strategy.appendField(locator, this, "operationCode", buffer, theProcessingCode);
        }
        {
            RegResponseDataType theRegResponseData;
            theRegResponseData = this.getRegResponseData();
            strategy.appendField(locator, this, "regResponseData", buffer, theRegResponseData);
        }
        {
            ResponseDataType theSalesResponseData;
            theSalesResponseData = this.getSalesResponseData();
            strategy.appendField(locator, this, "salesResponseData", buffer, theSalesResponseData);
        }
        {
            ResponseDataType theDepositResponseData;
            theDepositResponseData = this.getDepositResponseData();
            strategy.appendField(locator, this, "depositResponseData", buffer, theDepositResponseData);
        }
        {
            Float theVersion;
            theVersion = this.getVersion();
            strategy.appendField(locator, this, "version", buffer, theVersion);
        }
        return buffer;
    }

}
